[package]
name = "mwe"
version = "0.1.0"
authors = ["Emanuele Dalla Longa (infinitesnow) <3xplosive.g@gmail.com>"]
edition = "2018"

[dependencies.winit]
version = "~0.23.0"
default-features = false
features = [ "x11" ]
